name: watchos-jobs

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build_with_11_7_0_WATCHOS:
    name: "Xcode version 11.7.0, Target tvOS [armv7k, arm64_32] Target SDK 5.0"
    runs-on: macos-latest
    env:
      PLATFORM: WATCHOS
      DEPLOYMENT_TARGET: "5.0"
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '11.7.0'
    - name: Build
      run: ./.github/build.sh
  build_with_12_5_1_SIMULATOR_WATCHOS:
    name: "Xcode version 12_5_1, Target tvOS [x86_64] Target SDK 7.0"
    runs-on: macos-latest
    env:
      PLATFORM: SIMULATOR_WATCHOS
      DEPLOYMENT_TARGET: "7.0"
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.5.1'
    - name: Build
      run: ./.github/build.sh